###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Regenerate:   python -m ramulator codegen
###############################################################################
from .first_touch_page_coloring import FirstTouchPageColoring
from .no_translation import NoTranslation

__all__ = ['FirstTouchPageColoring', 'NoTranslation']
