###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/translation/impl/first_touch_page_coloring_m4.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class FirstTouchPageColoringM4(Component):
    impl = "FirstTouchPageColoringM4"
    max_addr = Param(int, required=True, cpp_type="Addr_t")
    page_size = Param(int, default=4096, cpp_type="Addr_t")
    ba_bit_offset = Param(int, default=13)
    channels = Param(int, default=1)
    channel_interleave_size = Param(int, default=64, cpp_type="Addr_t")
    seed = Param(int, default=0)
    tolerant_bas = Param(list, required=True, cpp_type="std::vector<int>")
    num_cores = Param(int, required=True)
    tolerant_cores = Param(list, required=True, cpp_type="std::vector<int>")
