###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/translation/impl/first_touch_page_coloring.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class FirstTouchPageColoring(Component):
    impl = "FirstTouchPageColoring"
    max_addr = Param(int, required=True, cpp_type="Addr_t")
    page_size = Param(int, default=4096, cpp_type="Addr_t")
    ba_bit_offset = Param(int, default=13)
    reduced_ba = Param(int, default=0)
    num_cores = Param(int, required=True)
    tolerant_cores = Param(list, required=True, cpp_type="std::vector<int>")
