###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/refresh/impl/lpddr6_lethe_m4.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class LPDDR6LetheM4(Component):
    impl = "LPDDR6LetheM4"
    refresh_multiplier = Param(float, default=1.0)
    ba_ratios = Param(list, required=True, cpp_type="std::vector<double>")
    schedule = Param(str, default='round_robin')
    debug = Param(bool, default=False)
